name: Nuxt.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # 更新到 v4

    - name: Use Node.js
      uses: actions/setup-node@v4  # 更新到 v4
      with:
        node-version: '20'  # 确保使用 Node.js 20

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Generate
      run: npm run generate

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
